M48
; DRILL file {KiCad (7.0.0-0)} date Tuesday, March 07, 2023 00:12:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-07T00:12:58+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1417
%
G90
G05
T1
X1.1331Y-1.0117
X1.9Y-3.3762
X3.3606Y-4.9841
X6.4724Y-1.0117
X6.4724Y-4.9841
T0
M30
